FROM team.suturo.de:9420/suturo/euroc-suturo-base

MAINTAINER Moritz Horstmann <mhorst@tzi.de>

USER root
# Install any video drivers here, eg:

#### NVIDIA
# RUN apt-get install -y binutils && apt-get clean
# ADD files/NVIDIA-DRIVER.run /tmp/NVIDIA-DRIVER.run
# RUN sh /tmp/NVIDIA-DRIVER.run -a -N --ui=none --no-kernel-module && rm /tmp/NVIDIA-DRIVER.run

USER suturo