#!/bin/bash
SCRIPTS=$(dirname "$0")
SCENESVERSION="1.0.25"
if [ "`dpkg -l | grep euroc | grep scenes | grep $SCENESVERSION`" == "" ]
	then echo Wrong scenes version installed! Currently supported version is $SCENESVERSION. Exiting.
	exit
fi
echo Changing camera image size to 800x600
sudo cp $SCRIPTS/../scenes/common_sensors_800x600.yml /opt/euroc_c2s1/scenes/common_sensors.yml
echo Finished!
