#!/bin/bash
SCRIPTS=$(dirname "$0")
echo Installing custom tasks
sudo cp $SCRIPTS/../scenes/head_mover.yml /opt/euroc_c2s1/scenes/
sudo cp $SCRIPTS/../scenes/scenes.yml /opt/euroc_c2s1/scenes/scenes.yml
# sudo echo "- head_mover.yml" >> /opt/euroc_c2s1/scenes/scenes.yml	
echo Finished!
