#!/bin/bash
SCRIPTS=$(dirname "$0")
SCENESVERSION="1.0.25"
if [ "`dpkg -l | grep euroc | grep scenes | grep $SCENESVERSION`" == "" ]
	then echo Wrong scenes version installed! Currently supported version is $SCENESVERSION. Exiting.
	exit
fi
echo Installing custom tasks
sudo cp $SCRIPTS/../scenes/*suturo.yml /opt/euroc_c2s1/scenes/
sudo cp $SCRIPTS/../scenes/customScenes.yml /opt/euroc_c2s1/scenes/scenes.yml
echo Finished!
